/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#162839",
        "primary-container": "#2c3e50",
        "on-primary": "#ffffff",
        "on-primary-container": "#96a9be",
        secondary: "#59605b",
        "secondary-container": "#dae1db",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5d6460",
        tertiary: "#451819",
        "tertiary-container": "#602d2d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#dc9493",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b2",
        "on-tertiary-fixed": "#370d0f",
        "on-tertiary-fixed-variant": "#6d3737",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        surface: "#f9f9fc",
        "surface-dim": "#dadadc",
        "surface-bright": "#f9f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f6",
        "surface-container": "#eeeef0",
        "surface-container-high": "#e8e8ea",
        "surface-container-highest": "#e2e2e5",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#43474c",
        "inverse-surface": "#2f3133",
        "inverse-on-surface": "#f0f0f3",
        outline: "#74777d",
        "outline-variant": "#c4c6cd",
        background: "#f9f9fc",
        "on-background": "#1a1c1e",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        serif: ["Source Serif 4", "Georgia", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.0625rem",
        md: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "24px",
        margin: "32px",
      },
    },
  },
  plugins: [],
};
